### ISSUE TITLE
Automatically set ovirtVmName in the flexvolume config when deploying

### ISSUE THREAD

**Issue by rgolangh** [oVirt/ovirt-openshift-extensions#52]
Problem:
The flexvolume driver uses an entry in the config file that is used when attaching volumes to the running
nodes. The entry is `ovirtVmName` and is really the name of ovirt's VM in ovirt which is running the actual kubelet. During deploy time, using the apb, it is missing, because what we have is a container that copy over
the binary and conf file to the kubelet plugin directory.

Solution:
1. The container `ovirt-flexvolume-driver` will use a env parameter `NODENAME` and will append
     its value to the conf file
2. The replica-set that deploy all those deploy containers will use the downward-api to inject the
    spec.nodeName` into the conainer under the name mentioned in 1

```
    env:
      - name: NODENAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
```
